### ISSUE TITLE
Python 2.6 Compatibility

### ISSUE THREAD

**Issue by baileytj3** [KyleJamesWalker/yamlsettings#13]
Are there any other incompatibilities with Python 2.6 besides the '{}' in the format strings? I have modified the formatting strings so that they are compatible with Python 2.6 and I have not (yet) had any issues with yamlsettings in Python 2.6. I have not testing to make sure everything works in 2.7 and 3.4 though.

Would it be possible to update the format strings to be 2.6 compatible? I could submit a pull request if that would be better.

Thanks.

**Comment by KyleJamesWalker** [comment]
Please submit and I'll take a look, joy of python compatibility "fun", thanks!

I should be able to get it merged and release a new version within a day or two (assuming work doesn't give me enough time to check it sooner)

Otherwise I may be able to add 2.6 support this weekend (without PR to speed me up)

**Comment by KyleJamesWalker** [comment]
#14 has been merged, and released https://pypi.python.org/pypi/yamlsettings/0.2.5
